comit

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -48,12 +48,16 @@ jobs:
       # =========================
       - name: Setup SSH
         run: |
-            mkdir -p ~/.ssh
-            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
-            chmod 600 ~/.ssh/id_rsa
-            ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
-        env:
-          SERVER_HOST: ${{ secrets.SERVER_HOST }}
+         mkdir -p ~/.ssh
+         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+         chmod 600 ~/.ssh/id_rsa
+
+         if [ -z "${{ secrets.SERVER_HOST }}" ]; then
+           echo "ERROR: SERVER_HOST secret is empty"
+          exit 1
+         fi
+
+          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts
       # =========================
       # CREATE SERVER DIRECTORIES
       # =========================
@@ -80,15 +84,15 @@ jobs:
       # =========================
       # DEPLOY BACKEND
       # =========================
-      - name: Deploy Node.js Backend
+      - name: Deploy Node.js API
         run: |
           rsync -avz \
           --exclude=node_modules \
           --exclude=.env \
           --exclude=uploads \
           --exclude=.git \
-          backend/ \
-          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/html/gens.demoquaeretech.in/backend/
+          api/ \
+          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/html/gens.demoquaeretech.in/api/
 
 
       # =========================
@@ -98,7 +102,7 @@ jobs:
         run: |
           ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
 
-            cd /var/www/html/gens.demoquaeretech.in/backend
+            cd /var/www/html/gens.demoquaeretech.in/api
 
             npm ci --omit=dev
 
